### ISSUE TITLE
Search not running on Lidarr

### ISSUE THREAD

**Issue by rowdyNP** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#69]
I have this running through custom scripts on unRAID. Works beautifully in Sonarr and Radarr but not Lidarr. Below is the verbose output. Any help appreciated as this is a fantastic script :) 

```
[33;1mVERBOSE: Reading config file[0m
[33;1mVERBOSE: Valid application specified[0m
[33;1mVERBOSE: Validating configuration for Discord Webhook[0m
[33;1mVERBOSE: Validating configuration for Lidarr[0m
[33;1mVERBOSE: Validating "API Key" for Lidarr[0m
[33;1mVERBOSE: Validating "Count" for Lidarr[0m
[33;1mVERBOSE: Validating "Monitored" for Lidarr[0m
[33;1mVERBOSE: Validating "ArtistStatus" for Lidarr[0m
[33;1mVERBOSE: Validating "Quality Profile Name" for Lidarr[0m
[33;1mVERBOSE: Validating "Tag Name" for Lidarr[0m
[33;1mVERBOSE: Validating "Ignore Tags" for Lidarr[0m
[33;1mVERBOSE: Validating "Unattended" for Lidarr[0m
[33;1mVERBOSE: Validating "URL" for Lidarr[0m
Configuration for Lidarr is valid
[33;1mVERBOSE: No Discord Webhook specified, no notifications will be sent[0m
[33;1mVERBOSE: Requested HTTP/1.1 GET with 0-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Requested HTTP/1.1 GET with 0-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Found tag name "upgradinatorr" with Id "4"[0m
[33;1mVERBOSE: No artist status specified for Lidarr[0m
[33;1mVERBOSE: No Ignore Tags specified[0m
[33;1mVERBOSE: No Quality Profile Name specified[0m
Starting Lidarr search
Config - Lidarr - URL: http://192.168.4.99:8686
Config - Lidarr - Monitored: True
Config - Lidarr - Status: All
Config - Lidarr - Unattended: False
Config - Lidarr - Limit: 3
Config - Lidarr - Tag Name: upgradinatorr
Config - Lidarr - Tag ID: 4
Config - Lidarr - Ignore Tag: None
Config - Lidarr - Quality Profile Name: None
To do lol
```

**Comment by angrycuban13** [comment]
@rowdyNP, I believe I've fixed this bug. If you wish to test before I merge the PR, please do the following:
 - git pull
 - git switch "v3.0"
 - Run the script
 ```powershell
pwsh -File //path/to/script/upgradinatorr.ps1 -ApplicationList radarr
```

**Comment by rowdyNP** [comment]
Thank you for working on this. I've seen all your activity and hard work lately. I really appreciate it. I'm still running into problems with Lidarr being stubborn. The [December 2023 commit](https://github.com/angrycuban13/Just-A-Bunch-Of-Starr-Scripts/issues/71#issuecomment-2352225377) still works. I'm not sure why v3 isn't playing nice.

Script output:
```
[33;1mVERBOSE: Performing the operation "Reading configuration file" on target "/mnt/cache/appdata/scripts/Just-A-Bunch-Of-Starr-Scripts/Upgradinatorr/upgradinatorr.conf".[0m
[33;1mVERBOSE: Performing the operation "Checking that no quotes are present in the configuration file" on target "/mnt/cache/appdata/scripts/Just-A-Bunch-Of-Starr-Scripts/Upgradinatorr/upgradinatorr.conf".[0m
[33;1mVERBOSE: Performing the operation "Validating "Notifications" section" on target "/mnt/cache/appdata/scripts/Just-A-Bunch-Of-Starr-Scripts/Upgradinatorr/upgradinatorr.conf".[0m
[33;1mVERBOSE: Performing the operation "Validating application" on target "Lidarr".[0m
[33;1mVERBOSE: Lidarr is a supported application[0m
[33;1mVERBOSE: Performing the operation "Validating "Lidarr" section" on target "/mnt/cache/appdata/scripts/Just-A-Bunch-Of-Starr-Scripts/Upgradinatorr/upgradinatorr.conf".[0m
[33;1mVERBOSE: Validating "ApiKey" for "Lidarr"[0m
[33;1mVERBOSE: Validating "Count" for "Lidarr"[0m
[33;1mVERBOSE: Validating "Monitored" for "Lidarr"[0m
[33;1mVERBOSE: Validating "ArtistStatus" for "Lidarr"[0m
[33;1mVERBOSE: Validating "TagName" for "Lidarr"[0m
[33;1mVERBOSE: Validating "Unattended" for "Lidarr"[0m
[33;1mVERBOSE: Validating "URL" for "Lidarr"[0m
[33;1mVERBOSE: Lidarr settings are configured correctly[0m
Lidarr is a valid application and its configuration has been validated
[33;1mVERBOSE: Performing the operation "Retrieving API version" on target "Lidarr".[0m
[33;1mVERBOSE: Requested HTTP/1.1 GET with 0-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Performing the operation "Retrieving Tag ID" on target "Lidarr".[0m
[33;1mVERBOSE: Requested HTTP/1.1 GET with 0-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Performing the operation "Retrieving Tag ID to ignore" on target "Lidarr".[0m
[33;1mVERBOSE: Performing the operation "Retrieving Quality Profile ID" on target "Lidarr".[0m
[33;1mVERBOSE: Performing the operation "Retrieving all media" on target "Lidarr".[0m
[33;1mVERBOSE: Requested HTTP/1.1 GET with 0-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Retrieved a total of 468 media items from Lidarr[0m
[33;1mVERBOSE: Performing the operation "Filtering media based on configuration values" on target "Lidarr".[0m
[33;1mVERBOSE: Filtering media to only include media without the tag "upgradinatorr" and that are monitored[0m
[33;1mVERBOSE: Filtered media based on configuration values, found 345 media items to process for Lidarr[0m
[33;1mVERBOSE: Performing the operation "Selecting media to search based on count" on target "Lidarr".[0m
[33;1mVERBOSE: Filtering media based on count: 3[0m
[33;1mVERBOSE: Performing the operation "Starting search for media items" on target "Lidarr".[0m
[33;1mVERBOSE: Requested HTTP/1.1 POST with 49-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mWARNING: Lidarr responded with 500 when executing Start-StarrMediaSearch function[0m
[31;1mException: [0m/mnt/cache/appdata/scripts/Just-A-Bunch-Of-Starr-Scripts/Upgradinatorr/upgradinatorr-v3.ps1:552[0m
[31;1m[0m[36;1mLine |[0m
[31;1m[0m[36;1m[36;1m 552 | [0m … [36;1mthrow "Server responded with `"Internal Server Error`" fo[0m …[0m
[31;1m[0m[36;1m[36;1m[0m[36;1m[0m[36;1m | [31;1m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[31;1m[0m[36;1m[36;1m[0m[36;1m[0m[36;1m[31;1m[31;1m[36;1m | [31;1mServer responded with "Internal Server Error" for Lidarr. Please check your configuration[0m
```

Lidarr Logs:
```
2025-01-03 09:24:49.5|Info|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was challenged.
2025-01-03 09:24:56.7|Warn|LidarrErrorPipeline|System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.artistId | LineNumber: 0 | BytePositionInLine: 36.

[v2.8.2.4493] System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.artistId | LineNumber: 0 | BytePositionInLine: 36.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartArray' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& value)
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at Lidarr.Api.V1.Commands.CommandController.StartCommand(CommandResource commandResource) in ./Lidarr.Api.V1/Commands/CommandController.cs:line 69
   at lambda_method316(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Lidarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/UrlBaseMiddleware.cs:line 29
   at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2025-01-03 09:24:56.8|Fatal|LidarrErrorPipeline|Request Failed. POST /api/v1/command

[v2.8.2.4493] System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.artistId | LineNumber: 0 | BytePositionInLine: 36.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartArray' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& value)
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at Lidarr.Api.V1.Commands.CommandController.StartCommand(CommandResource commandResource) in ./Lidarr.Api.V1/Commands/CommandController.cs:line 69
   at lambda_method316(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Lidarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Lidarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Lidarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Lidarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Lidarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/UrlBaseMiddleware.cs:line 29
   at Lidarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Lidarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by angrycuban13** [comment]
I don't use Lidarr so I was hoping it would behave nicely :) let me spin up a local instance to see what the API is expecting when you kick off a search. I know Sonarr is particular about the way you send series through the `command` endpoint.

**Comment by angrycuban13** [comment]
@rowdyNP okay go ahead and do a `git pull`. Lidarr only supports one artist search at a time, so I separated each search request.

**Comment by rowdyNP** [comment]
The search kicked off successfully! The artists that were searched for didn't populate as with Sonarr and Radarr but it gets the job done! Thanks!

```
[33;1mVERBOSE: Performing the operation "Reading configuration file" on target "/mnt/cache/appdata/scripts/Just-A-Bunch-Of-Starr-Scripts/Upgradinatorr/upgradinatorr.conf".[0m
[33;1mVERBOSE: Performing the operation "Checking that no quotes are present in the configuration file" on target "/mnt/cache/appdata/scripts/Just-A-Bunch-Of-Starr-Scripts/Upgradinatorr/upgradinatorr.conf".[0m
[33;1mVERBOSE: Performing the operation "Validating "Notifications" section" on target "/mnt/cache/appdata/scripts/Just-A-Bunch-Of-Starr-Scripts/Upgradinatorr/upgradinatorr.conf".[0m
[33;1mVERBOSE: Performing the operation "Validating application" on target "Lidarr".[0m
[33;1mVERBOSE: Lidarr is a supported application[0m
[33;1mVERBOSE: Performing the operation "Validating "Lidarr" section" on target "/mnt/cache/appdata/scripts/Just-A-Bunch-Of-Starr-Scripts/Upgradinatorr/upgradinatorr.conf".[0m
[33;1mVERBOSE: Validating "ApiKey" for "Lidarr"[0m
[33;1mVERBOSE: Validating "Count" for "Lidarr"[0m
[33;1mVERBOSE: Validating "Monitored" for "Lidarr"[0m
[33;1mVERBOSE: Validating "ArtistStatus" for "Lidarr"[0m
[33;1mVERBOSE: Validating "TagName" for "Lidarr"[0m
[33;1mVERBOSE: Validating "Unattended" for "Lidarr"[0m
[33;1mVERBOSE: Validating "URL" for "Lidarr"[0m
[33;1mVERBOSE: Lidarr settings are configured correctly[0m
Lidarr is a valid application and its configuration has been validated
[33;1mVERBOSE: Performing the operation "Retrieving API version" on target "Lidarr".[0m
[33;1mVERBOSE: Requested HTTP/1.1 GET with 0-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Performing the operation "Retrieving Tag ID" on target "Lidarr".[0m
[33;1mVERBOSE: Requested HTTP/1.1 GET with 0-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Performing the operation "Retrieving Tag ID to ignore" on target "Lidarr".[0m
[33;1mVERBOSE: Performing the operation "Retrieving Quality Profile ID" on target "Lidarr".[0m
[33;1mVERBOSE: Performing the operation "Retrieving all media" on target "Lidarr".[0m
[33;1mVERBOSE: Requested HTTP/1.1 GET with 0-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Retrieved a total of 468 media items from Lidarr[0m
[33;1mVERBOSE: Performing the operation "Filtering media based on configuration values" on target "Lidarr".[0m
[33;1mVERBOSE: Filtering media to only include media without the tag "upgradinatorr" and that are monitored[0m
[33;1mVERBOSE: Filtered media based on configuration values, found 342 media items to process for Lidarr[0m
[33;1mVERBOSE: Performing the operation "Selecting media to search based on count" on target "Lidarr".[0m
[33;1mVERBOSE: Filtering media based on count: 3[0m
[33;1mVERBOSE: Performing the operation "Starting search for media items" on target "Lidarr".[0m
[33;1mVERBOSE: Requested HTTP/1.1 POST with 39-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Search started for 1 media items in Lidarr[0m
[33;1mVERBOSE: Requested HTTP/1.1 POST with 39-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Search started for 1 media items in Lidarr[0m
[33;1mVERBOSE: Requested HTTP/1.1 POST with 39-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Search started for 1 media items in Lidarr[0m
[33;1mVERBOSE: Performing the operation "Adding tag to media items" on target "Lidarr".[0m
[33;1mVERBOSE: Requested HTTP/1.1 PUT with 59-byte payload[0m
[33;1mVERBOSE: Received HTTP/1.1 response of content type application/json of unknown size[0m
[33;1mVERBOSE: Content encoding: utf-8[0m
[33;1mVERBOSE: Tag added to 3 media items in Lidarr[0m
[33;1mVERBOSE: Performing the operation "Sending notification to enabled services" on target "Lidarr".[0m
Search started for 3 media items in Lidarr:
-
-
-
```

**Comment by angrycuban13** [comment]
I'll fix that too, thanks for testing.

**Comment by angrycuban13** [comment]
![image](https://github.com/user-attachments/assets/ac3a4ac4-68e9-4827-b46a-2e64e239df16)
![image](https://github.com/user-attachments/assets/ab811541-baeb-4541-81e7-de56f74eae97)
LGTM. Thanks for testing!
